[package]
name = "reedex"
version = "0.1.0"
edition = "2018"

[dependencies]
reedline = { version = "0.26.0", features = ["bashisms", "sqlite"] }
crossterm = { version = "0.27.0", features = ["serde"] }
nu-ansi-term = "0.49.0"
